name: 'bi_hospital'
version: '1.0.0'
config-version: 2

profile: 'bi_hospital'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  bi_hospital:
    +materialized: view
    data_marts:
      +schema: data_marts
    olap:
      rolap:
        +materialized: view
      molap:
        +materialized: table
      holap:
        +materialized: view
