bi_clinico:
  target: prod
  outputs:
    prod:
      type: postgres
      host: ep-orange-sun-aiyh4lhb-pooler.c-4.us-east-1.aws.neon.tech
      user: neondb_owner
      password: npg_jr5fHxYAJU2S
      port: 5432
      dbname: neondb
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      search_path: public
      sslmode: require
